images:
- name: auditforwarder
  sourceRepository: https://github.com/metal-stack/audit-forwarder
  repository: ghcr.io/metal-stack/audit-forwarder
  tag: "v0.2.4"
- name: audittailer
  sourceRepository: https://github.com/fluent/fluentd
  repository: fluent/fluentd
  tag: "v1.12"
